"""create records table

Revision ID: b0ef1a8836f6
Revises: 
Create Date: 2026-07-10 20:31:06.448510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0ef1a8836f6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('natural_key', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disp_code', sa.Text(), nullable=False),
    sa.Column('disposition', sa.Text(), nullable=False),
    sa.Column('final_radio_code', sa.Text(), nullable=False),
    sa.Column('final_call_type', sa.Text(), nullable=False),
    sa.Column('hundred_block_addr', sa.Text(), nullable=False),
    sa.Column('grid', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('natural_key', name='uq_records_natural_key')
    )
    op.create_index('ix_records_occurred_at', 'records', ['occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_records_occurred_at', table_name='records')
    op.drop_table('records')
    # ### end Alembic commands ###
